### ISSUE TITLE
hola, hay un problema con el link del taller de git y github

### ISSUE THREAD

**Issue by RobertoSalgadoC** [LaunchX-InnovaccionVirtual/onboarding-github-launchx#11]
el link del taller de git y github no funciona, lo pueden reparar por favor

**Comment by FernandaOchoa** [comment]
Hola, revisamos ambos links y funcionan perfectamente 👍

**Comment by RobertoSalgadoC** [comment]
hola, Me pasa el link por favor, a mi me redirige aquí https://github.com/LaunchX-InnovaccionVirtual/onboarding-github-launchx/blob/main/taller-de-github-101
![image](https://user-images.githubusercontent.com/51171516/153099412-f78f144d-acdc-4933-8bcc-58491d802fca.png)
