### ISSUE TITLE
Problema al entrar al taller de git 

### ISSUE THREAD

**Issue by JuanCarloshdz** [LaunchX-InnovaccionVirtual/onboarding-github-launchx#12]
Saludos al ingresar a https://github.com/LaunchX-InnovaccionVirtual/onboarding-github-launchx/blob/main/taller-de-github-101 me salie el siguiente error 
![image](https://user-images.githubusercontent.com/61675951/153739663-be05dd2d-6737-4b2b-9b6c-1c1dfc63a5cd.png)

**Comment by LeonardoGutierrezV** [comment]
Buenos dias.
Cuando entras a tu pagina principal de git deberia verse asi.

![image](https://user-images.githubusercontent.com/88008394/153754408-19ff1b59-9157-4261-b466-9a5300cbcbfa.png)

Picale el botón de ver organización

![image](https://user-images.githubusercontent.com/88008394/153754442-6a07f4b6-9a7e-48e1-b611-5f7683c63891.png)

Y ahi podras ver el acceso directo al onboarding.

Si tampoco te deja hacerlo puede ser un problema con los permisos
